dist: xenial # default 2019-09-01
sudo: false # build faster?
language: java
jdk:
  - openjdk8
  - openjdk11

git:
  depth: 3
  quiet: true

services:
  - docker

env:
  global:
    # Common
    - APP_NAME=travis-demo
    - MY_REPO_SLUG=archongum/travis-demo
    # Maven
    - MAVEN_BUILD_ARGS="-DskipTests=false -Dmaven.javadoc.skip=true -Dcheckstyle.skip=false -B -V -T 2.0C"
    # Docker
    - BUILD_DOCKER=true
    - DOCKER_USER=dockergum
    - secure: "OmZCQ7botr7R/vI/Z0Zjb/7Cn9ohAIHmygD+nhpdALZWA6bRJo8qQEyeZt8E7NF6NGQXa8XZYGrqCezGayDKXGKTbNggPWbG8wL8lLK3wqwAhMskmaecXBQvhC4I17YZ+nC9DvWSUD7r9IYvpM5aN0f7SX76SDnJZ2k7JNbdoyVBhO4BijaGrkeIzDlxC1PUisNobltKlpCjXliWCQ55RfDy0oipJz2sJ88UYIf5DwIyHoJCIzBWcya+UN0BgjiWASSVDUDGEgNXDe5qxm25FH6JLQh/tz5nMjnSjGl4E/u3QT3vBXcH+dOOzxgbOfGNJMSaKH0kTvw4vbEzXlWguK0GZdpXhOuRRi7+J/znfX9TjZPzsYjEH4B92C13CLmj7DxukckkdLk45znmpx9tnf8RhWqgPcxTL0tfnXMD/VHDaXC0J788vbQ/jsmV5ZW14xqJYpLhWLTisxR3SfhbAVW+re1wi4LPz6XZuABs2Qng0wN+6FZN9ZW7hrRyRUxVi8IlXqJqS3BL9D6DnJvQrEiIbAyNBTufUEu7HSZhWgQcsOIWtxosE6Fq1sMNhd/4JAKCMLhLjsLDkKhX9MNIwcaH9UbqiEgJbIcu2puxRneuhlaakpYrjszpWycSJOgmQnCrcgaoTOThIvAhsUBGZpSQDyogr2NEKNS0EbIi1kY=" # DOCKER_PASS
    # Heroku
    - DEPLOY_HEROKU=true
    - HEROKU_APP_NAME=archongum-travis-demo
    - secure: "gKZJgSWvItqXqOMZJt1VnsdsrLDHvCnreBQ2capRpjOmxGy8U623GNBPBVlD90H+SuIjh7R7qZLzotlfzKpPeq0yqOWq3xWHx3AGp0SEAdk1+eHxr/Yze2L8DSGKgY/MtzvZkFffp+qHM422pByiInviB3FczYkVGpiJCuK9Nrjjxy4lMAFQqyGO2SOPLwOoEZHrvrLsolVVkWhhAa6zFtNaPmXP0GFT310F0PJhL2zAI0vLf16YgSYbj9m5LVx/ZJS9Cj+Esc0OZpkd5dzgLB4D9fvU/u2qXH1uskJJ9A7ifIkD7r/sNgXb5JqKpk+6ceRbOyms+4rqMnaA3TFGK3aU7xi108Qus3OVKzZVNOJJsCXglI+G2jDs8VJHdswcpokMqNIdKXQvo1iUjX8T0mSP3plngeeJXHnocVfZ/YV5t3cFnRsu/ZsM91BCdNvCtqXboZ6PGn9NiRe2ED+6RKgjhrTLhwg3A+hqEsru0H/PABAcZ1t2C9kQZZRCdyIO4G10vZOlrKA5g30nbwuCHVz9o2Jo8rd/2X5pRZc+b98qBIkAW+r0rvynpag7negDk4bbzYdaAI8Mm7fKDTt3Pe2dh+nhCYpNqoEgT5YhXm8BPfwgw8kpU7fZq3/CKMXXfifenHd26OwGN1Wmttxa5UkSRZAL7zaeesoccZMKAXs=" # HEROKU_API_KEY

cache:
  directories:
    - $HOME/.m2/repository

before_install:
  - chmod +x mvnw

install: skip

script:
  - ./mvnw clean install $MAVEN_BUILD_ARGS

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - |
    if [ "$BUILD_DOCKER" = "true" ] && [ "$TRAVIS_JDK_VERSION" = "openjdk8" ] && [ "$TRAVIS_REPO_SLUG" = "$MY_REPO_SLUG" ] ; then
      docker login -u $DOCKER_USER -p $DOCKER_PASS
      export TAG=`if [ "$TRAVIS_BRANCH" = "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
      export IMAGE_NAME=$DOCKER_USER/$APP_NAME
      docker build -t $IMAGE_NAME:${TRAVIS_COMMIT::6} .
      docker tag $IMAGE_NAME:${TRAVIS_COMMIT::6} $IMAGE_NAME:$TAG
      docker push $IMAGE_NAME
    fi

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: $HEROKU_APP_NAME
  on:
    condition: 
      - $DEPLOY_HEROKU = true # space needed
      - $TRAVIS_REPO_SLUG = $MY_REPO_SLUG
    branch: master
    jdk: openjdk8
