kind: ConfigMap
apiVersion: v1
metadata:
  name: travis-demo-cm
data:
  application.yml: |-
    spring:
      application:
        name: "travis-demo"
    server:
      port: 8080
  application-uat.yml: |-
    spring:
      application:
        name: "travis-demo-uat"
        mykey: uat
  application-prd.yml: |-
    spring:
      application:
        name: "travis-demo-prd"
        mykey: prd
