name: CI - Maven Docker

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: |
          # build
          mvn -B package --file pom.xml
          # code coverage
          bash <(curl -s https://codecov.io/bash)
        
      - uses: docker/login-action@v2
      - name: Login to Aliyun Registry
        if: ${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}} == "main"
        with:
          registry: registry.cn-guangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_REGISTRY_USERNAME }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}
      - name: Upload to docker hub
        env:
          IMAGE_NAME: registry.cn-guangzhou.aliyuncs.com/archongum/travis-demo:v1
        run: |
          # show size
          du -sh ./*
          # build
          docker build . --file Dockerfile --tag $IMAGE_NAME
          # show images
          docker images | head -n 10
          # push
          docker push $IMAGE_NAME
